// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFSf1c7HGLFD_ll2XLsj3fhNCRiYENl4',
    appId: '1:617927541648:web:94503330ef1bbdb834a915',
    messagingSenderId: '617927541648',
    projectId: 'chat-app-58079',
    authDomain: 'chat-app-58079.firebaseapp.com',
    storageBucket: 'chat-app-58079.appspot.com',
    measurementId: 'G-7L9PSF8G4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsp54LW4FUky7pSD2Hs8TgAcsk107kN94',
    appId: '1:617927541648:android:01c9b1faf340cca434a915',
    messagingSenderId: '617927541648',
    projectId: 'chat-app-58079',
    storageBucket: 'chat-app-58079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKx1E2eCgJYfxgjY2KUZe280uW0oa-hgU',
    appId: '1:617927541648:ios:219f236dfddaf8ad34a915',
    messagingSenderId: '617927541648',
    projectId: 'chat-app-58079',
    storageBucket: 'chat-app-58079.appspot.com',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKx1E2eCgJYfxgjY2KUZe280uW0oa-hgU',
    appId: '1:617927541648:ios:219f236dfddaf8ad34a915',
    messagingSenderId: '617927541648',
    projectId: 'chat-app-58079',
    storageBucket: 'chat-app-58079.appspot.com',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRFSf1c7HGLFD_ll2XLsj3fhNCRiYENl4',
    appId: '1:617927541648:web:afb8a83a380387e234a915',
    messagingSenderId: '617927541648',
    projectId: 'chat-app-58079',
    authDomain: 'chat-app-58079.firebaseapp.com',
    storageBucket: 'chat-app-58079.appspot.com',
    measurementId: 'G-68JMXY5409',
  );

}